#!/bin/sh

set -e

BASE_DIR="$(dirname "$0")/../../"
test -d ${BASE_DIR}
cd ${BASE_DIR}

make_dir_list() {
  FILE_LIST=$1
  OLD_PREFIX=$2
  NEW_PREFIX=$3
  RESULT=""
  for FILE in $FILE_LIST; do
    FILE_DIR=$(dirname "${FILE}")
    echo "Found Dir $FILE_DIR from $FILE\n" >&2
    DIR=${NEW_PREFIX}${FILE_DIR#${OLD_PREFIX}}
    RESULT="${RESULT} ${DIR}"
  done
  echo -n "${RESULT}" | xargs -n1 | sort -u | xargs
}

SOURCE_FILES=$(find src/ -name '*.c' -o -name '*.h')
TEST_FILES=$(find "test/" -name '*.c')

OBJECT_DIRS=$(make_dir_list "${SOURCE_FILES}" src build/nuvm)
TEST_DIRS=$(make_dir_list "${TEST_FILES}" "test" "build/test")
REPORT_DIRS=$(make_dir_list "${TEST_FILES}" 'test' 'build/test-reports')

mkdir -p $OBJECT_DIRS $TEST_DIRS $REPORT_DIRS
